### ISSUE TITLE
Using XWJOY with GOG XWCD leaves me unable to create or select pilot

### ISSUE THREAD

**Issue by Barraken** [pagej97/xwjoy-redux#1]
While using XWJOY for the first time, I noticed that I was unable to even create or select a pilot at the registration desk. I was playing the CD edition from GOG and using a Logitech Extreme 3D Pro. The attached video will demonstrate the behavior displayed at the registration desk.

https://user-images.githubusercontent.com/123152615/213651401-5bc91f42-bb74-421e-9d97-f90e95541790.mp4

**Comment by pagej97** [comment]
Thanks for the video -- it's very helpful.  Looks like it's detecting throttle movement?  Might try:
 - Move the joystick throttle to a different location, and see if the phantom input stops.
 - Recalibrating; just move data/xwjoy.cal out of the directory, and generate a new one.
 - Taking a look at dosbox configuration (I'm using timed=false, though I haven't noticed any difference between the modes).

**Comment by pagej97** [comment]
OK; I think I reproduced your issue.  I suspect it's reading your rudders as throttle input.

Try this.
1) Set swap34=true in dosbox_xwingcd.conf:
```
[joystick]
...
swap34=true
```
2) Delete xwjoy.cal.
3) Relaunch game and calibrate throttle when prompted.

**Comment by Barraken** [comment]
That did the trick. All is mostly well, except that I can’t twist to roll. I can do it the old way (hold the 2 button and move stick left or right), but I want to roll by twisting the stick. Any ideas?

**Comment by pagej97** [comment]
**Re. rolling with joystick rudder axis:**
I took a look, and the rudder axis is supported by DOSBox, but I'm looking at the keyboard references for X-Wing and for Tie Fighter, and I don't see any control for roll other than holding button two while yawing.  If the game offered a keyboard control for rolling, we could use DOSBox's "Mapper" to map axis 4 to the appropriate keys, but I don't see one.  I think this is just a limitation of the game, and I don't see an easy & satisfactory fix.

**Comment by pagej97** [comment]
Glad swapping joystick axes via dosbox_xwingcd.conf (+ recalibrating) worked.

**Comment by pagej97** [comment]
Glad swapping joystick axes via dosbox_xwingcd.conf (+ recalibrating) worked.

**Comment by Barraken** [comment]
It’s supposed to be CTRL + the arrow keys, depending on the direction of the roll.
